### PR TITLE
Disable use of .curlrc when downloading sources

### PR DESCRIPTION
**Pull request by afh**
from sourceforge.

I ran into issues with the Makefile when downloads xz, forward to and hosted on sourceforge, as the curl would download a HTML page instead of the source archive.
Adding a wget user-agent fixed the issue for me.

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [ ] I have read the **CONTRIBUTING.md** file
- [ ] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — COMMENTED** [review]
I can't see anything *obviously* problematic about this, but I'd feel a lot better if I could reproduce the problem you're seeing myself. I'm not having any problems with using curl (without the user agent) to download xz-5.4.2 or xz-5.2.6, How is this manifesting for you?

**Comment by afh** [comment]
It's manifesting as a HTML file that is downloaded instead of the actual source archive. Maybe this differs from the geographic region that the download is initiated; I reside in :eu:.
```
% curl -sLO https://tukaani.org/xz/xz-5.4.2.tar.gz
% file xz-5.4.2.tar.gz
xz-5.4.2.tar.gz: HTML document text, Unicode text, UTF-8 text, with very long lines (1113)
% head -5 xz-5.4.2.tar.gz
<!doctype html>

<html class="no-js" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
% curl -sLO -A wget/1.23.2 https://tukaani.org/xz/xz-5.4.2.tar.gz
% file xz-5.4.2.tar.gz
xz-5.4.2.tar.gz: gzip compressed data, max compression, from Unix, original size modulo 2^32 10905600
% tar ztf xz-5.4.2.tar.gz| head -5
xz-5.4.2/
xz-5.4.2/debug/
xz-5.4.2/debug/translation.bash
xz-5.4.2/debug/sync_flush.c
xz-5.4.2/debug/repeat.c
```

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Interesting - I'm normally in Australia, and I'm currently in the US for PyCon, and I haven't seen this problem in either location. However, I can't see any harm to adding the user agent; all I'd ask is that you add a comment to the definition so that there's a paper trail explaining why it was added (otherwise it's likely to get "cleaned up" in future because it's not obvious why it's needed).

**Comment by afh** [comment]
Apologies, I just realised that this is specific to my setup as I have set a custom user-agent set in `~/.curlrc` that I forgot about.

Would you agree that there is benefit in adding the `--disable` option as the first parameter to curl? It causes curl to **not** read and use the config file. This would make all curl calls behave the same regardless on any customizations that users may have.

**Comment by freakboy3742** [comment]
Ah! That explains it. In which case - yes - disabling any local config would definitely be worthwhile.

**Comment by afh** [comment]
I'll update this PR accordingly, would you want a comment as a paper trail on this change too?

Also if I may ask: What were your personal highlights of PyCon?

**Review by freakboy3742 — APPROVED** [review]
Looks good - I don't think the explanatory note is needed in this case; "disable the user's config" is a lot more intuitive than "use the Wget user agent because Sourceforge returns raw HTML".

As for PyCon: My highlight of PyCon is always the people - doubly so this year, because I haven't seen so many of them in person for almost 4 years.

**Pull request merged**
