### PR TITLE
Avoid building OpenSSL docs

### PR DESCRIPTION
**Pull request by afh**
The openssl `all` targets includes building the documentation, which seems unnecessary for this project.

## PR Checklist:

- [ ] All new features have been tested
- [ ] All new features have been documented
- [ ] I have read the **CONTRIBUTING.md** file
- [ ] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — APPROVED** [review]
Agreed - we don't need to build docs. Thanks for the fix!

**Comment by afh** [comment]
FYI: I believe the `build_sw` target is OpenSSL 3.x specific, fortunately OpenSSL 1.1.1 provides the `build_libs`, which seems to also omit the docs. Would you like to see this PR be amended, so that that depending on the OpenSSL version the right build target is used or would a comment in the Makefile suffice?

**Comment by freakboy3742** [comment]
I don't think there's a need to adapt this PR to support OpenSSL 1.1.1; That version is almost EOL, and we've been able to port all our currently supported branched (3.8+) to use OpenSSL 3. The only reason we've got OpenSSL 1.1.1 references still in the code is because of a need to support (very old) versions of Cryptography, which is something we need to fix by updating our ability to support newer versions of Cryptography.

**Comment by afh** [comment]
Thanks for the context on OpenSSL 1.1.1 and merging this PR.

**Pull request merged**
