### PR TITLE
Include curses in macOS support package

### PR DESCRIPTION
**Pull request by SamSchott**
As discussed in https://github.com/beeware/briefcase/issues/516, this PR includes curses in the support package.

MacOS already comes with ncurses bundled so we only need to include Python package and extension module, increasing the size of the support package by roughly 0.3 MB.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — APPROVED** [review]
👍 I've updated the patch so that it's compatible with the embedded executable changes from beeware/briefcase#525; otherwise, thanks for the patch!

**Comment by SamSchott** [comment]
Seems like curses was removed again from the Python 3.10 macOS build. Was this intentional?

**Comment by SamSchott** [comment]
Hm, I think this was a side effect of 7b35fc5.

**Comment by freakboy3742** [comment]
Oh drat. No, it wasn't intentional; I got overzealous with some refactoring. 

We (by which I mean, probably I) really do need to work out how to do an automated release test on these builds...

**Comment by SamSchott** [comment]
This may be a stupid question, but why did excluding any of the other .so files not cause any problems?

**Pull request merged**
